//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser_Assignment1.NumberSorter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberSorter.INumberSorterService")]
    public interface INumberSorterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSorterService/sort", ReplyAction="http://tempuri.org/INumberSorterService/sortResponse")]
        string sort(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumberSorterService/sort", ReplyAction="http://tempuri.org/INumberSorterService/sortResponse")]
        System.Threading.Tasks.Task<string> sortAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumberSorterServiceChannel : Browser_Assignment1.NumberSorter.INumberSorterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumberSorterServiceClient : System.ServiceModel.ClientBase<Browser_Assignment1.NumberSorter.INumberSorterService>, Browser_Assignment1.NumberSorter.INumberSorterService {
        
        public NumberSorterServiceClient() {
        }
        
        public NumberSorterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumberSorterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberSorterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumberSorterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sort(string s) {
            return base.Channel.sort(s);
        }
        
        public System.Threading.Tasks.Task<string> sortAsync(string s) {
            return base.Channel.sortAsync(s);
        }
    }
}
